services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: travel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - travel-network
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: travel-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - travel-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: travel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: travel_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: travel_user
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - travel-network

networks:
    travel-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
